# Generated by Django 5.0.10 on 2024-12-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                max_length=200, null=True, verbose_name="телеграм айди"
            ),
        ),
    ]
