# Generated by Django 5.0.10 on 2024-12-07 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="pleasant_habit",
            field=models.BooleanField(
                default=False, verbose_name="Признак приятной привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="started_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата начала привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(verbose_name="Время выполнения"),
        ),
    ]
